#!/usr/bin/env sh
# vim: syntax=sh et ts=2 sw=2 sts=2

main ()
{
  if [ $# -lt 1 ]; then
    cat <<EOF
$(basename "$0") [theme]

Available themes: $(sed -rn 's,^\[theme-([a-zA-Z0-9]+)\],\1,p' theme.conf | tr '\n' ' ')
EOF
    exit 0
  fi
  _theme=$1; themer/themer.py --config theme.conf --theme "$_theme" && {
    if pgrep -x Hyprland >/dev/null 2>&1; then
      killall -q waybar    && waybar &
      killall -q hyprpaper && hyprpaper &
      killall -q mako      && mako &
      hyprctl reload
    fi
  }
}

main "$@"
